title: HFF - 前端代码规范
subtitle: "Front-End Coding Guidelines"
description: "Best Coding Guidelines For Front-End Developer."
author: HFF Team
language: zh-cn
timezone: Asia/Shanghai
url: http://lee84233.github.io/
root: /html-guide/
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:lee84233/html-guide.git
  branch: gh-pages

disqus_shortname:
twitter: 
github: lee84233/html-guide
gh:
  user: lee84233
  repo: html-guide
